### ISSUE TITLE
Admin UI not loading

### ISSUE THREAD

**Issue by lbprinzr** [pocketbase/pocketbase#7715]
After updating PB from v0.36.9 to v0.38.2 I observed that the admin UI doesn‘t load anymore on my side. My frontend is working proper. I run the environment in a docker. I am using an iPad Pro with Safari and even Chrome (latest version 148) didn‘t load. I also tried https://pocketbase.io/_/ with the same result. From another device (Mac) pocketbase.io/_/ works.

It ends up like that:

<img width="2388" height="1452" alt="Image" src="https://github.com/user-attachments/assets/d13e697a-567f-4467-958a-6ac787a37c05" />

With debug tool, I got this error message:
TypeError: RegExp.escape is not a function. (In 'RegExp.escape(r[e])', 'RegExp.escape' is undefined)

Is there a way to see more logs what the issue is exact?

Many thanks for your support.

**Comment by ganigeorgiev** [comment]
> I am using an iPad Pro with Safari and even Chrome (latest version 148) didn‘t load. 

I'm right now using Chrome 148.0.7778.178 and it works perfectly fine for me (I've also tested it with Firefox 150+).

There were past similar reports and they ended up being a result of using an old browser (see [`RegExp.escape` support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/escape#browser_compatibility)).

So either you are not reporting the used browser correctly or there is something else Safari specific but I have no access to a Mac device to reproduce it.

If you can provide more details, I'll try to investigate it further but as of now it works correctly for me.

**Comment by ganigeorgiev** [comment]
After researching it further, I bet that the issue is caused by an outdated Safari installed on the device. Based on Apple store guidelines (and iOS OS policy) it seems that all browsers are required to use the WebKit engine that comes with the preinstalled Safari so I guess it is possible that even if you use the latest Chrome the above to still fail if it delegates the JS execution to the outdated WebKit on the device.

So, try to update your Safari to the latest one (I'm not familiar with the Mac ecosystem but it seems that the Safari team recently decided to sync the 2026 year with the release numbering and there is now jump from Safari 18 to 26).

**Comment by lbprinzr** [comment]
Thanks for the fast feedback, here the screenshot of chrome and the version:

<img width="2388" height="1604" alt="Image" src="https://github.com/user-attachments/assets/ef4ebd1f-40fa-417f-b27c-53359bb47b4d" />****
It stays with that page, spinning the wheel. But why it fails then with Chrome?

**Comment by ganigeorgiev** [comment]
> But why it fails then with Chrome?

Because on iOS it is most likely using the WebKit engine available with the builtin Safari/OS _(see my [earlier comment](https://github.com/pocketbase/pocketbase/issues/7715#issuecomment-4554269482))_.

What is the used Safari version on the device? Did you try to update it?

**Comment by lbprinzr** [comment]
Then I will try to update, yes indeed I us an older version of Safari. I hope and believe this will solved it if you don‘t see any other issues. Many thanks for your support.

**Comment by lbprinzr** [comment]
I can confirm, update helped, all working fine now.
